
name = "quotely"
main = "src/index.ts"
compatibility_date = "2025-03-11"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "quotely"
database_id = "ecb18634-8f0f-4a5b-b8d2-9002363f093c"
