export * from './author.route';
export * from './authors.route';
export * from './create.route';
export * from './error.route';
export * from './quote.last.route';
export * from './quote.random.route';
export * from './quotes.route';
export * from './tag.route';
export * from './tags.route';
